#!/bin/bash
# update-data.sh - Downloads and processes zip code timezone data
# Source: https://github.com/seanpianka/Zipcodes (MIT License)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
TEMP_DIR=$(mktemp -d)

cleanup() {
    rm -rf "$TEMP_DIR"
}
trap cleanup EXIT

echo "Downloading zip code data..."
curl -sL "https://raw.githubusercontent.com/seanpianka/Zipcodes/master/zipcodes/zips.json.bz2" -o "$TEMP_DIR/zips.json.bz2"

echo "Decompressing..."
bunzip2 -k "$TEMP_DIR/zips.json.bz2"

echo "Extracting zip code -> timezone mapping..."
# Extract only zip_code and timezone, filter out null timezones, output as simple JSON object
jq -c '[.[] | select(.timezone != null) | {(.zip_code): .timezone}] | add' "$TEMP_DIR/zips.json" > "$TEMP_DIR/ziptz.json"

echo "Generating data.go..."
cat > "$PROJECT_DIR/data.go" << 'HEADER'
// Code generated by scripts/update-data.sh. DO NOT EDIT.
// Source: https://github.com/seanpianka/Zipcodes (MIT License)

package ziptz

var zipToTimezone = map[string]string{
HEADER

# Convert JSON to Go map entries
jq -r 'to_entries | .[] | "\t\"\(.key)\": \"\(.value)\","' "$TEMP_DIR/ziptz.json" >> "$PROJECT_DIR/data.go"

echo "}" >> "$PROJECT_DIR/data.go"

# Format the generated file
gofmt -w "$PROJECT_DIR/data.go"

# Count entries
COUNT=$(jq 'length' "$TEMP_DIR/ziptz.json")
echo "Done! Generated $COUNT zip code entries."
